import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

/**
 * MonthlySnapshot — Stores pre-computed monthly financial analysis.
 * Generated by monthlyAnalysisJob.js on day 1 of each month.
 * Used by aiController.js in 'deep' mode to avoid hitting Gemini on every request.
 */
export const MonthlySnapshot = sequelize.define('MonthlySnapshot', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    period: {
        // First day of the analyzed month: e.g. '2026-03-01' for March 2026
        type: DataTypes.DATEONLY,
        allowNull: false,
        unique: true
    },
    computed_metrics: {
        // Computed by Node.js: { totalIncome, totalExpenses, balance, savingsRate, topCategories, vsLastMonth }
        type: DataTypes.JSONB,
        allowNull: true
    },
    gemini_narrative: {
        // Short diagnostic paragraph generated by Gemini
        type: DataTypes.TEXT,
        allowNull: true
    },
    gemini_alerts: {
        // Array of 3 prioritized alerts
        type: DataTypes.JSONB,
        allowNull: true
    },
    gemini_recommendations: {
        // Array of 2 actionable recommendations
        type: DataTypes.JSONB,
        allowNull: true
    },
    tokens_used: {
        // Tokens consumed generating this snapshot (audit trail)
        type: DataTypes.INTEGER,
        allowNull: true
    }
}, {
    tableName: 'monthly_snapshots',
    timestamps: true,
    createdAt: 'created_at',
    updatedAt: false,
    indexes: [
        { fields: ['period'], using: 'BTREE', order: 'DESC' }
    ]
});
