-- Migration 002: Cleanup Duplicate Telegram Links Constraints
-- Drops redundant constraints generated by repeated Sequelize sync() calls

DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'telegram_links'::regclass
          AND conname ~ '^telegram_links_chatId_key[0-9]+$'
    ) LOOP
        EXECUTE 'ALTER TABLE telegram_links DROP CONSTRAINT ' || quote_ident(r.conname);
        RAISE NOTICE 'Dropped duplicate constraint %', r.conname;
    END LOOP;
END $$;
